"""add product_type default_image_url

Revision ID: 14d09f724048
Revises: f37fa036c844
Create Date: 2026-07-06 15:57:40.911558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14d09f724048'
down_revision: Union[str, None] = 'f37fa036c844'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_types', sa.Column('default_image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_types', 'default_image_url')
    # ### end Alembic commands ###
