"""add language preference to admin users and customers

Revision ID: 2266f6f41f9a
Revises: 2404140e221e
Create Date: 2026-07-04 02:52:37.565557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2266f6f41f9a'
down_revision: Union[str, None] = '2404140e221e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_users', sa.Column('language', sa.String(length=5), server_default='ru', nullable=False))
    op.add_column('customers', sa.Column('language', sa.String(length=5), server_default='ru', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'language')
    op.drop_column('admin_users', 'language')
    # ### end Alembic commands ###
