"""add customer telegram_username

Revision ID: 4357efdd7a81
Revises: 14d09f724048
Create Date: 2026-07-06 16:37:33.470847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4357efdd7a81'
down_revision: Union[str, None] = '14d09f724048'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('telegram_username', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'telegram_username')
    # ### end Alembic commands ###
