"""make cart_item unique constraint exclude soft-deleted rows

Revision ID: 55ad4e546df3
Revises: 4357efdd7a81
Create Date: 2026-07-06 17:32:58.682362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55ad4e546df3'
down_revision: Union[str, None] = '4357efdd7a81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_cart_item_product', 'cart_items', type_='unique')
    op.create_index('uq_cart_item_product', 'cart_items', ['cart_id', 'product_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_cart_item_product', table_name='cart_items', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint('uq_cart_item_product', 'cart_items', ['cart_id', 'product_id'])
    # ### end Alembic commands ###
