"""add category is_featured and image_url

Revision ID: a1b5d9e2a93f
Revises: 55ad4e546df3
Create Date: 2026-07-06 18:48:04.490663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b5d9e2a93f'
down_revision: Union[str, None] = '55ad4e546df3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('is_featured', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('categories', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'image_url')
    op.drop_column('categories', 'is_featured')
    # ### end Alembic commands ###
