"""catalog pim engine: product types attribute sets reference data collections labels documents videos

Revision ID: a7a032238a52
Revises: 2266f6f41f9a
Create Date: 2026-07-04 15:23:12.161166

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7a032238a52'
down_revision: Union[str, None] = '2266f6f41f9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Bootstrap ids for the fallback ProductType/AttributeSet backfilled onto any
# pre-existing products (this project's only pre-existing row is demo/test
# data). scripts/seed_catalog.py inserts the real product types afterward.
_BOOTSTRAP_ATTRIBUTE_SET_ID = str(uuid.uuid4())
_BOOTSTRAP_PRODUCT_TYPE_ID = str(uuid.uuid4())


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attribute_groups',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('attribute_sets',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('product_labels',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('badge_color', sa.String(length=20), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('reference_values',
    sa.Column('reference_type', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_type', 'code', name='uq_reference_value_type_code')
    )
    op.create_index('ix_reference_values_type', 'reference_values', ['reference_type'], unique=False)
    op.create_table('attribute_group_translations',
    sa.Column('attribute_group_id', sa.UUID(), nullable=False),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['attribute_group_id'], ['attribute_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attribute_group_id', 'locale', name='uq_attribute_group_translation')
    )
    op.create_index('ix_attribute_group_translations_parent', 'attribute_group_translations', ['attribute_group_id'], unique=False)
    op.create_table('collections',
    sa.Column('manufacturer_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_collections_manufacturer_id', 'collections', ['manufacturer_id'], unique=False)
    op.create_table('product_label_translations',
    sa.Column('product_label_id', sa.UUID(), nullable=False),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_label_id'], ['product_labels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_label_id', 'locale', name='uq_product_label_translation')
    )
    op.create_index('ix_product_label_translations_parent', 'product_label_translations', ['product_label_id'], unique=False)
    op.create_table('product_types',
    sa.Column('attribute_set_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['attribute_set_id'], ['attribute_sets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('reference_value_translations',
    sa.Column('reference_value_id', sa.UUID(), nullable=False),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reference_value_id'], ['reference_values.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_value_id', 'locale', name='uq_reference_value_translation')
    )
    op.create_index('ix_reference_value_translations_parent', 'reference_value_translations', ['reference_value_id'], unique=False)
    op.create_table('attribute_definition_translations',
    sa.Column('attribute_definition_id', sa.UUID(), nullable=False),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['attribute_definition_id'], ['attribute_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attribute_definition_id', 'locale', name='uq_attribute_definition_translation')
    )
    op.create_index('ix_attribute_definition_translations_parent', 'attribute_definition_translations', ['attribute_definition_id'], unique=False)
    op.create_table('attribute_set_items',
    sa.Column('attribute_set_id', sa.UUID(), nullable=False),
    sa.Column('attribute_definition_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('default_value', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['attribute_definition_id'], ['attribute_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['attribute_set_id'], ['attribute_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attribute_set_id', 'attribute_definition_id', name='uq_attribute_set_item')
    )
    op.create_index('ix_attribute_set_items_set_id', 'attribute_set_items', ['attribute_set_id'], unique=False)
    op.create_table('collection_translations',
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'locale', name='uq_collection_translation')
    )
    op.create_index('ix_collection_translations_parent', 'collection_translations', ['collection_id'], unique=False)
    op.create_table('product_type_translations',
    sa.Column('product_type_id', sa.UUID(), nullable=False),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_type_id'], ['product_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_type_id', 'locale', name='uq_product_type_translation')
    )
    op.create_index('ix_product_type_translations_parent', 'product_type_translations', ['product_type_id'], unique=False)
    op.create_table('product_documents',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Enum('MANUAL', 'CERTIFICATE', 'WARRANTY_CARD', 'INSTALLATION_INSTRUCTIONS', 'EXPLODED_DIAGRAM', name='product_document_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=150), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_product_documents_product_id', 'product_documents', ['product_id'], unique=False)
    op.create_table('product_label_assignments',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('product_label_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_label_id'], ['product_labels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'product_label_id', name='uq_product_label_assignment')
    )
    op.create_index('ix_product_label_assignments_product_id', 'product_label_assignments', ['product_id'], unique=False)
    op.create_table('product_translations',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('meta_title', sa.String(length=255), nullable=True),
    sa.Column('meta_description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'locale', name='uq_product_translation')
    )
    op.create_index('ix_product_translations_product_id', 'product_translations', ['product_id'], unique=False)
    op.create_table('product_videos',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('video_type', sa.Enum('YOUTUBE', 'MP4', 'EXTERNAL', name='product_video_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_product_videos_product_id', 'product_videos', ['product_id'], unique=False)
    op.add_column('attribute_definitions', sa.Column('attribute_group_id', sa.UUID(), nullable=True))
    op.add_column('attribute_definitions', sa.Column('reference_type', sa.String(length=50), nullable=True))
    op.add_column('attribute_definitions', sa.Column('validation_regex', sa.String(length=500), nullable=True))
    op.add_column('attribute_definitions', sa.Column('min_value', sa.Numeric(precision=18, scale=6), nullable=True))
    op.add_column('attribute_definitions', sa.Column('max_value', sa.Numeric(precision=18, scale=6), nullable=True))
    op.create_foreign_key(None, 'attribute_definitions', 'attribute_groups', ['attribute_group_id'], ['id'], ondelete='SET NULL')
    op.add_column('product_attributes', sa.Column('value_reference_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'product_attributes', 'reference_values', ['value_reference_id'], ['id'], ondelete='SET NULL')
    op.add_column('products', sa.Column('product_type_id', sa.UUID(), nullable=True))
    op.add_column('products', sa.Column('collection_id', sa.UUID(), nullable=True))
    op.add_column('products', sa.Column('barcode', sa.String(length=64), nullable=True))
    # add_column (unlike create_table) doesn't auto-create the backing
    # Postgres enum type, so it's created explicitly here first.
    postgresql.ENUM('DRAFT', 'ACTIVE', 'ARCHIVED', name='product_status').create(
        op.get_bind(), checkfirst=True
    )
    op.add_column('products', sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='product_status'), server_default='DRAFT', nullable=False))
    op.add_column('products', sa.Column('sale_price', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('products', sa.Column('future_price', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('products', sa.Column('future_price_activates_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('products', sa.Column('currency', sa.String(length=3), server_default='UZS', nullable=False))
    op.add_column('products', sa.Column('reserved_quantity', sa.Integer(), server_default='0', nullable=False))
    op.add_column('products', sa.Column('is_unlimited_stock', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('products', sa.Column('low_stock_threshold', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('canonical_url_override', sa.String(length=500), nullable=True))
    op.add_column('products', sa.Column('seo', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('products', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('russian', coalesce(name, '') || ' ' || coalesce(sku, '') || ' ' || coalesce(slug, '') || ' ' || coalesce(barcode, '') || ' ' || coalesce(description, ''))", persisted=True), nullable=True))
    op.create_index('ix_products_collection_id', 'products', ['collection_id'], unique=False)
    op.create_index('ix_products_product_type_id', 'products', ['product_type_id'], unique=False)
    op.create_index('ix_products_search_vector', 'products', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('ix_products_status', 'products', ['status'], unique=False)
    op.create_unique_constraint(None, 'products', ['barcode'])
    op.create_foreign_key(None, 'products', 'collections', ['collection_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'products', 'product_types', ['product_type_id'], ['id'], ondelete='RESTRICT')

    # --- data backfill for pre-existing rows (bootstrap fallback type, then
    # derive status from the old is_active flag) before tightening constraints ---
    op.execute(
        f"""
        INSERT INTO attribute_sets (id, code, name, description, created_at, updated_at)
        VALUES ('{_BOOTSTRAP_ATTRIBUTE_SET_ID}', 'general', 'General',
                'Fallback attribute set for products not yet assigned a specific product type.',
                now(), now())
        """
    )
    op.execute(
        f"""
        INSERT INTO product_types (id, attribute_set_id, code, name, sort_order, is_active, created_at, updated_at)
        VALUES ('{_BOOTSTRAP_PRODUCT_TYPE_ID}', '{_BOOTSTRAP_ATTRIBUTE_SET_ID}', 'general', 'General',
                0, true, now(), now())
        """
    )
    op.execute(f"UPDATE products SET product_type_id = '{_BOOTSTRAP_PRODUCT_TYPE_ID}' WHERE product_type_id IS NULL")
    op.execute("UPDATE products SET status = 'ACTIVE' WHERE is_active = true")

    op.alter_column('products', 'product_type_id', nullable=False)
    op.drop_column('products', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, server_default='true', nullable=False))
    op.execute("UPDATE products SET is_active = (status = 'ACTIVE')")
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_index('ix_products_status', table_name='products')
    op.drop_index('ix_products_search_vector', table_name='products', postgresql_using='gin')
    op.drop_index('ix_products_product_type_id', table_name='products')
    op.drop_index('ix_products_collection_id', table_name='products')
    op.drop_column('products', 'search_vector')
    op.drop_column('products', 'seo')
    op.drop_column('products', 'canonical_url_override')
    op.drop_column('products', 'low_stock_threshold')
    op.drop_column('products', 'is_unlimited_stock')
    op.drop_column('products', 'reserved_quantity')
    op.drop_column('products', 'currency')
    op.drop_column('products', 'future_price_activates_at')
    op.drop_column('products', 'future_price')
    op.drop_column('products', 'sale_price')
    op.drop_column('products', 'status')
    postgresql.ENUM(name='product_status').drop(op.get_bind(), checkfirst=True)
    op.drop_column('products', 'barcode')
    op.drop_column('products', 'collection_id')
    op.drop_column('products', 'product_type_id')
    op.drop_constraint(None, 'product_attributes', type_='foreignkey')
    op.drop_column('product_attributes', 'value_reference_id')
    op.drop_constraint(None, 'attribute_definitions', type_='foreignkey')
    op.drop_column('attribute_definitions', 'max_value')
    op.drop_column('attribute_definitions', 'min_value')
    op.drop_column('attribute_definitions', 'validation_regex')
    op.drop_column('attribute_definitions', 'reference_type')
    op.drop_column('attribute_definitions', 'attribute_group_id')
    op.drop_index('ix_product_videos_product_id', table_name='product_videos')
    op.drop_table('product_videos')
    op.drop_index('ix_product_translations_product_id', table_name='product_translations')
    op.drop_table('product_translations')
    op.drop_index('ix_product_label_assignments_product_id', table_name='product_label_assignments')
    op.drop_table('product_label_assignments')
    op.drop_index('ix_product_documents_product_id', table_name='product_documents')
    op.drop_table('product_documents')
    op.drop_index('ix_product_type_translations_parent', table_name='product_type_translations')
    op.drop_table('product_type_translations')
    op.drop_index('ix_collection_translations_parent', table_name='collection_translations')
    op.drop_table('collection_translations')
    op.drop_index('ix_attribute_set_items_set_id', table_name='attribute_set_items')
    op.drop_table('attribute_set_items')
    op.drop_index('ix_attribute_definition_translations_parent', table_name='attribute_definition_translations')
    op.drop_table('attribute_definition_translations')
    op.drop_index('ix_reference_value_translations_parent', table_name='reference_value_translations')
    op.drop_table('reference_value_translations')
    op.drop_table('product_types')
    op.drop_index('ix_product_label_translations_parent', table_name='product_label_translations')
    op.drop_table('product_label_translations')
    op.drop_index('ix_collections_manufacturer_id', table_name='collections')
    op.drop_table('collections')
    op.drop_index('ix_attribute_group_translations_parent', table_name='attribute_group_translations')
    op.drop_table('attribute_group_translations')
    op.drop_index('ix_reference_values_type', table_name='reference_values')
    op.drop_table('reference_values')
    op.drop_table('product_labels')
    op.drop_table('attribute_sets')
    op.drop_table('attribute_groups')
    # ### end Alembic commands ###
