"""make store settings about_text localized

Revision ID: dd3d40ef2a34
Revises: e1a86f34016e
Create Date: 2026-07-08 16:38:43.378134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd3d40ef2a34'
down_revision: Union[str, None] = 'e1a86f34016e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'store_settings', 'about_text',
        existing_type=sa.TEXT(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
        postgresql_using="CASE WHEN about_text IS NULL THEN NULL ELSE jsonb_build_object('ru', about_text) END",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'store_settings', 'about_text',
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.TEXT(),
        existing_nullable=True,
        postgresql_using="about_text->>'ru'",
    )
    # ### end Alembic commands ###
