"""add store settings about_text

Revision ID: e1a86f34016e
Revises: a1b5d9e2a93f
Create Date: 2026-07-08 16:19:40.906512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1a86f34016e'
down_revision: Union[str, None] = 'a1b5d9e2a93f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_settings', sa.Column('about_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_settings', 'about_text')
    # ### end Alembic commands ###
