"""add telegram bot settings, order manager notes, customer notification prefs, product recommendations and analytics events

Revision ID: f37fa036c844
Revises: b0b3b1d8b514
Create Date: 2026-07-06 02:14:04.907698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f37fa036c844'
down_revision: Union[str, None] = 'b0b3b1d8b514'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_analytics_events',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('VIEW', 'ADD_TO_CART', name='analytics_event_type'), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_product_analytics_events_event_type', 'product_analytics_events', ['event_type'], unique=False)
    op.create_index('ix_product_analytics_events_product_id', 'product_analytics_events', ['product_id'], unique=False)
    op.create_table('product_recommendations',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('recommended_product_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.Enum('RELATED', 'ACCESSORY', 'FREQUENTLY_BOUGHT_TOGETHER', name='recommendation_type'), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommended_product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'recommended_product_id', 'relation_type', name='uq_product_recommendation')
    )
    op.create_index('ix_product_recommendations_product_id', 'product_recommendations', ['product_id'], unique=False)
    op.add_column('customers', sa.Column('notifications_enabled', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('orders', sa.Column('manager_notes', sa.Text(), nullable=True))
    op.add_column('store_settings', sa.Column('bot_name', sa.String(length=200), nullable=True))
    op.add_column('store_settings', sa.Column('bot_username', sa.String(length=200), nullable=True))
    op.add_column('store_settings', sa.Column('welcome_text', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('store_settings', sa.Column('welcome_image_url', sa.String(length=500), nullable=True))
    op.add_column('store_settings', sa.Column('menu_button_text', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('store_settings', sa.Column('pinned_announcement', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('store_settings', sa.Column('manager_telegram_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('store_settings', sa.Column('notification_templates', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_settings', 'notification_templates')
    op.drop_column('store_settings', 'manager_telegram_ids')
    op.drop_column('store_settings', 'pinned_announcement')
    op.drop_column('store_settings', 'menu_button_text')
    op.drop_column('store_settings', 'welcome_image_url')
    op.drop_column('store_settings', 'welcome_text')
    op.drop_column('store_settings', 'bot_username')
    op.drop_column('store_settings', 'bot_name')
    op.drop_column('orders', 'manager_notes')
    op.drop_column('customers', 'notifications_enabled')
    op.drop_index('ix_product_recommendations_product_id', table_name='product_recommendations')
    op.drop_table('product_recommendations')
    op.drop_index('ix_product_analytics_events_product_id', table_name='product_analytics_events')
    op.drop_index('ix_product_analytics_events_event_type', table_name='product_analytics_events')
    op.drop_table('product_analytics_events')
    # ### end Alembic commands ###
